"""adding model changes for email confirmation flag

Revision ID: 663e41065b02
Revises: c952d8aab314
Create Date: 2020-04-27 11:22:41.525253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '663e41065b02'
down_revision = 'c952d8aab314'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_email_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_email_verified')
    # ### end Alembic commands ###
