"""adding initial workings

Revision ID: c952d8aab314
Revises: 
Create Date: 2020-04-26 19:07:15.287476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c952d8aab314'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=64), nullable=True),
    sa.Column('user_landmark', sa.UnicodeText(), nullable=True),
    sa.Column('user_city', sa.Unicode(), nullable=True),
    sa.Column('user_state', sa.Unicode(), nullable=True),
    sa.Column('user_Country', sa.Unicode(), nullable=True),
    sa.Column('user_pincode', sa.Integer(), nullable=True),
    sa.Column('user_lat', sa.Float(), nullable=True),
    sa.Column('user_long', sa.Float(), nullable=True),
    sa.Column('user_intrested_field1', sa.Unicode(), nullable=True),
    sa.Column('user_intrested_field2', sa.Unicode(), nullable=True),
    sa.Column('user_intrested_field3', sa.Unicode(), nullable=True),
    sa.Column('user_intrested_field4', sa.Unicode(), nullable=True),
    sa.Column('user_social_profile_url', sa.Unicode(), nullable=True),
    sa.Column('user_email_adrs', sa.Unicode(), nullable=True),
    sa.Column('user_organisation_name', sa.Unicode(), nullable=True),
    sa.Column('user_if_Founder', sa.Boolean(), nullable=True),
    sa.Column('user_image', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_user_city'), 'users', ['user_city'], unique=False)
    op.create_index(op.f('ix_users_user_email_adrs'), 'users', ['user_email_adrs'], unique=True)
    op.create_index(op.f('ix_users_user_intrested_field1'), 'users', ['user_intrested_field1'], unique=False)
    op.create_index(op.f('ix_users_user_intrested_field2'), 'users', ['user_intrested_field2'], unique=False)
    op.create_index(op.f('ix_users_user_intrested_field3'), 'users', ['user_intrested_field3'], unique=False)
    op.create_index(op.f('ix_users_user_intrested_field4'), 'users', ['user_intrested_field4'], unique=False)
    op.create_index(op.f('ix_users_user_name'), 'users', ['user_name'], unique=False)
    op.create_table('cults',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cult_name', sa.Unicode(), nullable=True),
    sa.Column('cult_lat', sa.Float(), nullable=True),
    sa.Column('cult_long', sa.Float(), nullable=True),
    sa.Column('cult_work_field1', sa.Unicode(), nullable=True),
    sa.Column('cult_work_field2', sa.Unicode(), nullable=True),
    sa.Column('cult_work_field3', sa.Unicode(), nullable=True),
    sa.Column('cult_work_field4', sa.Unicode(), nullable=True),
    sa.Column('cult_landmark', sa.UnicodeText(), nullable=True),
    sa.Column('cult_city', sa.Unicode(), nullable=True),
    sa.Column('cult_state', sa.Unicode(), nullable=True),
    sa.Column('cult_country', sa.Unicode(), nullable=True),
    sa.Column('cult_pincode', sa.Integer(), nullable=True),
    sa.Column('cult_founder_id', sa.Integer(), nullable=False),
    sa.Column('cult_quote_line', sa.UnicodeText(), nullable=True),
    sa.Column('cult_image', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['cult_founder_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cults_cult_city'), 'cults', ['cult_city'], unique=False)
    op.create_index(op.f('ix_cults_cult_name'), 'cults', ['cult_name'], unique=False)
    op.create_index(op.f('ix_cults_cult_work_field1'), 'cults', ['cult_work_field1'], unique=False)
    op.create_index(op.f('ix_cults_cult_work_field2'), 'cults', ['cult_work_field2'], unique=False)
    op.create_index(op.f('ix_cults_cult_work_field3'), 'cults', ['cult_work_field3'], unique=False)
    op.create_index(op.f('ix_cults_cult_work_field4'), 'cults', ['cult_work_field4'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cult_id', sa.Integer(), nullable=False),
    sa.Column('post_content', sa.UnicodeText(), nullable=True),
    sa.Column('post_banner_image', sa.LargeBinary(), nullable=True),
    sa.Column('post_application_url', sa.Unicode(), nullable=True),
    sa.ForeignKeyConstraint(['cult_id'], ['cults.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cult_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cult_id'], ['cults.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registrations',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('cult_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cult_id'], ['cults.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registrations')
    op.drop_table('ratings')
    op.drop_table('posts')
    op.drop_index(op.f('ix_cults_cult_work_field4'), table_name='cults')
    op.drop_index(op.f('ix_cults_cult_work_field3'), table_name='cults')
    op.drop_index(op.f('ix_cults_cult_work_field2'), table_name='cults')
    op.drop_index(op.f('ix_cults_cult_work_field1'), table_name='cults')
    op.drop_index(op.f('ix_cults_cult_name'), table_name='cults')
    op.drop_index(op.f('ix_cults_cult_city'), table_name='cults')
    op.drop_table('cults')
    op.drop_index(op.f('ix_users_user_name'), table_name='users')
    op.drop_index(op.f('ix_users_user_intrested_field4'), table_name='users')
    op.drop_index(op.f('ix_users_user_intrested_field3'), table_name='users')
    op.drop_index(op.f('ix_users_user_intrested_field2'), table_name='users')
    op.drop_index(op.f('ix_users_user_intrested_field1'), table_name='users')
    op.drop_index(op.f('ix_users_user_email_adrs'), table_name='users')
    op.drop_index(op.f('ix_users_user_city'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
